version: '3.9'
services:
  plotterlab:
    build: .
    image: plotterlab:latest
    container_name: plotterlab
    ports:
      - "${HOST_PORT:-8082}:${CONTAINER_PORT:-8080}"
    environment:
      - NODE_ENV=production
      - PORT=${CONTAINER_PORT:-8080}
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:${CONTAINER_PORT:-8080}/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - ./presets:/app/presets:rw
      - ./plugins:/app/plugins:rw
      - ./public:/app/public:rw
    restart: unless-stopped
